name: Docker Image CI

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build . -t my-nextjs-app

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 my-nextjs-app

      - name: Wait for the application to start
        run: sleep 10  # Give the app some time to start

      - name: Test application
        run: |
          curl --fail http://localhost:3000 || exit 1

      - name: Deploy
        run: |
          # Your deployment logic here
          # You can use rsync or any other tool to deploy your app to your server
